window.ONAIRO = window.ONAIRO || {};

ONAIRO.blogCategories = [
  { id: 'all', label: 'All' },
  { id: 'website-design', label: 'Website Design' },
  { id: 'software-development', label: 'Software Development' },
  { id: 'school-management', label: 'School Management' },
  { id: 'business-growth', label: 'Business Growth' },
  { id: 'technology', label: 'Technology' },
  { id: 'seo', label: 'SEO' },
  { id: 'ai', label: 'AI' },
  { id: 'digital-marketing', label: 'Digital Marketing' },
];

ONAIRO.blogPosts = [
  {
    id: 'mobile-first-websites',
    slug: 'mobile-first-website-design-pakistan',
    title: 'Why Mobile-First Website Design Still Wins More Customers in Pakistan',
    description: 'Learn how mobile-first website design improves conversions for businesses with faster CTAs, trust, and WhatsApp lead paths.',
    category: 'website-design',
    date: '2026-07-10',
    minutes: 5,
    thumb: 'alt0',
    related: ['src/portfolio/index.html', 'src/services/index.html', 'src/pages/request-quote.html'],
  },
  {
    id: 'leave-spreadsheets',
    slug: 'when-to-replace-spreadsheets-with-custom-software',
    title: 'When to Leave Spreadsheets Behind for Custom Software',
    description: 'Signs your business has outgrown Excel and needs custom software for multi-user workflows, reporting, and fewer errors.',
    category: 'software-development',
    date: '2026-07-08',
    minutes: 7,
    thumb: 'alt1',
    related: ['src/services/index.html', 'src/products/index.html', 'src/pages/contact.html'],
  },
  {
    id: 'school-admin-hours',
    slug: 'school-management-software-reduce-admin-hours',
    title: 'How Schools Cut Admin Hours with Unified School Management Software',
    description: 'How offline school ERP tools like EduTrack reduce attendance, fee, payroll, and parent communication chaos.',
    category: 'school-management',
    date: '2026-07-05',
    minutes: 6,
    thumb: 'alt2',
    related: ['src/products/edutrack.html', 'src/products/index.html', 'src/pages/request-quote.html'],
  },
  {
    id: 'digital-transformation',
    slug: 'digital-transformation-playbook-for-growing-businesses',
    title: 'Digital Transformation That Actually Sticks',
    description: 'A practical sequencing playbook for websites, automation, and software products so digital change compounds.',
    category: 'business-growth',
    date: '2026-06-28',
    minutes: 8,
    thumb: 'alt3',
    related: ['src/pages/about.html', 'src/services/index.html', 'src/pages/contact.html'],
  },
  {
    id: 'industry-website-patterns',
    slug: 'high-converting-industry-website-design-patterns',
    title: 'Industry Websites: What High-Converting Demos Get Right',
    description: 'Conversion patterns from dental, law, gym, travel, and real estate website demos that turn visitors into leads.',
    category: 'website-design',
    date: '2026-06-20',
    minutes: 4,
    thumb: 'alt4',
    related: ['src/portfolio/index.html', 'src/pages/request-quote.html'],
  },
  {
    id: 'practical-ai',
    slug: 'practical-ai-integrations-for-small-businesses',
    title: 'Practical AI Integrations for Small and Mid-Size Teams',
    description: 'Where AI assistants and document intelligence pay off quickly — and where human judgment still matters.',
    category: 'ai',
    date: '2026-06-12',
    minutes: 6,
    thumb: 'alt5',
    related: ['src/services/index.html', 'src/pages/contact.html'],
  },
  {
    id: 'seo-for-service-businesses',
    slug: 'seo-for-service-businesses-pakistan',
    title: 'SEO for Service Businesses in Pakistan: A Practical Starting Checklist',
    description: 'Title tags, local SEO, portfolio pages, and internal linking tips for clinics, law firms, gyms, and agencies.',
    category: 'seo',
    date: '2026-06-02',
    minutes: 6,
    thumb: 'alt1',
    related: ['src/portfolio/index.html', 'src/pages/blog.html', 'src/pages/contact.html'],
  },
  {
    id: 'whatsapp-lead-systems',
    slug: 'whatsapp-lead-systems-for-business-websites',
    title: 'WhatsApp Lead Systems for Business Websites',
    description: 'How to turn website traffic into WhatsApp conversations without losing enquiry context or follow-ups.',
    category: 'digital-marketing',
    date: '2026-05-22',
    minutes: 5,
    thumb: 'alt3',
    related: ['src/services/index.html', 'src/pages/request-quote.html'],
  },
];
