/**
 * Unique landing content for services + industries.
 * Consumed by scripts/generate-landings.js
 */
module.exports = {
  site: "https://onairosolutions.com",
  services: [
    {
      slug: "website-development",
      icon: "🌐",
      title: "Website Development Pakistan | Professional Business Websites | Onairo Solutions",
      h1: "Website Development That Turns Visitors Into Clients",
      lead: "We build conversion-focused business websites with premium design, mobile-first performance, and SEO foundations — for brands that need more than a template.",
      meta: "Professional website development in Pakistan. Custom, SEO-ready, mobile-first websites with WhatsApp leads and fast performance by Onairo Solutions.",
      what: "A website should do more than look good. We design and develop marketing sites that explain your offer clearly, build trust quickly, and make contact effortless — on every device.",
      benefits: [
        ["Modern responsive design", "Layouts that feel premium on desktop, tablet, and mobile."],
        ["Fast loading", "Performance-minded builds that protect Core Web Vitals."],
        ["SEO-friendly structure", "Clean headings, schema-ready pages, and crawlable URLs."],
        ["Mobile-first UX", "CTAs and WhatsApp paths placed where Pakistani customers actually tap."],
        ["Secure delivery", "Hardened hosting practices and safe form handling."],
        ["Easy to manage", "Content sections structured for future updates without chaos."],
      ],
      tech: ["HTML5", "CSS3", "JavaScript", "Responsive Design", "Performance Optimization", "SEO Markup"],
      portfolioIds: ["dental", "lawfirm", "gym", "travel", "restaurant", "it"],
      links: [
        { href: "../industries/", label: "Industry Websites" },
        { href: "seo-services.html", label: "SEO Services" },
        { href: "ui-ux-design.html", label: "UI/UX Design" },
        { href: "../portfolio/index.html", label: "Portfolio" },
      ],
      faqs: [
        { q: "How long does a business website take?", a: "Most marketing websites launch in 1–3 weeks depending on pages, content readiness, and integrations." },
        { q: "Will my website work on mobile?", a: "Yes. Every site is designed mobile-first with clear CTAs and WhatsApp conversion paths." },
        { q: "Do you include SEO?", a: "We include technical SEO foundations: titles, meta, headings, sitemap-ready structure, and internal links. Ongoing SEO campaigns can be added separately." },
        { q: "Can you rebuild my old website?", a: "Yes. See our Website Redesign service for modernization while protecting brand equity and rankings." },
      ],
      theme: { accent: "#3B82F6", accent2: "#93C5FD", glow: "rgba(59,130,246,0.22)", pattern: "grid" },
    },
    {
      slug: "software-development",
      icon: "🧩",
      title: "Custom Software Development Pakistan | Onairo Solutions",
      h1: "Custom Software Built Around Your Workflows",
      lead: "Stop forcing your team into generic tools. We engineer software that matches how your business actually operates — with clarity, security, and room to grow.",
      meta: "Custom software development in Pakistan for internal tools, CRMs, operations platforms, and business systems by Onairo Solutions.",
      what: "From operations dashboards to client portals, we design systems that reduce spreadsheet chaos, improve accountability, and give leadership trustworthy numbers.",
      benefits: [
        ["Workflow-fit architecture", "Software shaped around your real processes — not the other way around."],
        ["Scalable codebase", "Built to expand as teams, branches, and features grow."],
        ["Role-based access", "Permissions that keep sensitive data controlled."],
        ["Integrations", "Connect accounting, WhatsApp, email, and third-party APIs."],
        ["Audit-ready history", "Track changes and actions when compliance matters."],
        ["Iteration-friendly", "Ship an MVP first, then expand with confidence."],
      ],
      tech: ["JavaScript", "Node.js", "Python", "FastAPI", "PostgreSQL", "REST APIs"],
      portfolioIds: ["it", "school", "realestate"],
      links: [
        { href: "desktop-application-development.html", label: "Desktop Apps" },
        { href: "ai-solutions.html", label: "AI Solutions" },
        { href: "../products/edutrack.html", label: "EduTrack Product" },
        { href: "../pages/request-quote.html", label: "Request Quote" },
      ],
      faqs: [
        { q: "When should we leave Excel behind?", a: "When multiple people edit shared files, reports break, and nobody trusts the latest version — custom software becomes cheaper than chaos." },
        { q: "Do you build MVPs?", a: "Yes. We scope a first version around one painful workflow, then expand." },
        { q: "Who owns the code?", a: "You do. Delivery includes handover documentation and deployable assets as agreed in the project scope." },
      ],
      theme: { accent: "#8B5CF6", accent2: "#C4B5FD", glow: "rgba(139,92,246,0.2)", pattern: "hex" },
    },
    {
      slug: "desktop-application-development",
      icon: "🖥️",
      title: "Desktop Application Development | Windows Apps Pakistan | Onairo Solutions",
      h1: "Desktop Applications for Offline-Ready Operations",
      lead: "When browsers are not enough, we build reliable Windows desktop software — fast, local-first, and designed for real office workflows.",
      meta: "Windows desktop application development in Pakistan. Offline-capable business apps with local data, printing, and hardware support by Onairo Solutions.",
      what: "EduTrack proves our approach: desktop software that stays useful when internet drops, printers matter, and staff need speed over browser friction.",
      benefits: [
        ["Offline resilience", "Critical work continues without a constant internet connection."],
        ["Native-feel UX", "Interfaces designed for keyboard-heavy office users."],
        ["Local data options", "Keep sensitive records on campus or company hardware."],
        ["Hardware support", "Printers, scanners, and QR workflows where needed."],
        ["Installer packaging", "Clean Windows installers for school and office PCs."],
        ["Update pathways", "Plan for patches and version rollouts."],
      ],
      tech: ["Electron", "JavaScript", "Local Databases", "Windows Packaging", "Auto-update Patterns"],
      portfolioIds: ["school", "it"],
      links: [
        { href: "../products/edutrack.html", label: "See EduTrack" },
        { href: "software-development.html", label: "Custom Software" },
        { href: "../industries/school-website-design.html", label: "School Websites" },
      ],
      faqs: [
        { q: "Is Windows your primary platform?", a: "Yes. Windows is our primary desktop target; cross-platform options can be evaluated per project." },
        { q: "Can desktop apps sync later?", a: "Yes. Many projects start offline-first and add controlled sync or LAN sharing when ready." },
      ],
      theme: { accent: "#10B981", accent2: "#6EE7B7", glow: "rgba(16,185,129,0.2)", pattern: "bars" },
    },
    {
      slug: "ecommerce-development",
      icon: "🛒",
      title: "Ecommerce Website Development Pakistan | Online Store Design | Onairo Solutions",
      h1: "Ecommerce Websites Built to Sell",
      lead: "Product catalogues, clear checkout paths, and mobile shopping experiences that help customers buy with confidence.",
      meta: "Ecommerce website development in Pakistan. Online stores with product catalogues, WhatsApp ordering, and conversion-focused design by Onairo Solutions.",
      what: "Whether you need a full cart experience or WhatsApp-assisted ordering, we design storefronts that showcase products and remove friction from purchase decisions.",
      benefits: [
        ["Product-first layouts", "Galleries and filters that help shoppers decide faster."],
        ["Mobile shopping UX", "Thumb-friendly browsing for Instagram and WhatsApp traffic."],
        ["Order pathways", "Cart checkout or assisted WhatsApp ordering — matched to your ops."],
        ["Trust signals", "Reviews, policies, and secure contact placement."],
        ["Catalogue structure", "Categories and variants organized for growth."],
        ["SEO product pages", "Indexable pages for collections and key SKUs."],
      ],
      tech: ["HTML5", "CSS3", "JavaScript", "Payment Integrations", "Product Schema"],
      portfolioIds: ["boutique", "restaurant"],
      links: [
        { href: "website-development.html", label: "Website Development" },
        { href: "seo-services.html", label: "SEO Services" },
        { href: "../industries/clothing-store-website.html", label: "Boutique Websites" },
      ],
      faqs: [
        { q: "Do you support WhatsApp ordering?", a: "Yes. Many Pakistani brands convert better with WhatsApp-assisted orders plus a polished catalogue site." },
        { q: "Can you integrate payments later?", a: "Yes. We can start with enquiry-led commerce and add gateways when you are ready." },
      ],
      theme: { accent: "#F59E0B", accent2: "#FCD34D", glow: "rgba(245,158,11,0.18)", pattern: "dots" },
    },
    {
      slug: "ui-ux-design",
      icon: "✨",
      title: "UI/UX Design Services Pakistan | Product & Website Design | Onairo Solutions",
      h1: "UI/UX Design That Feels Effortless and Converts",
      lead: "Interfaces and journeys crafted for clarity, trust, and action — from marketing sites to software products.",
      meta: "UI/UX design services in Pakistan for websites and software products. Wireframes, visual systems, and conversion-focused interfaces by Onairo Solutions.",
      what: "Great design is not decoration. We map user journeys, reduce friction, and create visual systems that make brands feel premium and usable.",
      benefits: [
        ["Conversion-minded layouts", "Hierarchy that guides eyes to the next step."],
        ["Accessible interfaces", "Readable contrast and keyboard-friendly patterns."],
        ["Design systems", "Reusable components for consistent growth."],
        ["Prototype validation", "Test flows before expensive development."],
        ["Brand presence", "Visual identity that feels intentional — not generic."],
        ["Handoff clarity", "Specs developers can actually implement."],
      ],
      tech: ["Design Systems", "Prototyping", "Accessibility Guidelines", "Motion Design", "Design Tokens"],
      portfolioIds: ["dental", "lawfirm", "hotel"],
      links: [
        { href: "website-development.html", label: "Website Development" },
        { href: "../portfolio/index.html", label: "See Portfolio" },
        { href: "website-redesign.html", label: "Website Redesign" },
      ],
      faqs: [
        { q: "Do you offer design-only projects?", a: "Yes. Design packages can be delivered alone or paired with development." },
        { q: "Do you redesign existing products?", a: "Yes. We audit friction points and rebuild journeys without discarding what already works." },
      ],
      theme: { accent: "#EC4899", accent2: "#F9A8D4", glow: "rgba(236,72,153,0.18)", pattern: "waves" },
    },
    {
      slug: "ai-solutions",
      icon: "🤖",
      title: "AI Solutions & Integration Pakistan | Onairo Solutions",
      h1: "Practical AI Solutions That Save Real Hours",
      lead: "We integrate AI where it creates measurable value — enquiry triage, document intelligence, assistants, and smarter internal tools.",
      meta: "AI solutions and integration in Pakistan. Practical LLM features, assistants, and automation embedded into business software by Onairo Solutions.",
      what: "Skip the hype. We identify workflows where AI removes repetitive work while keeping humans in control of final decisions.",
      benefits: [
        ["Faster support", "Draft replies and route enquiries intelligently."],
        ["Document intelligence", "Summaries and extraction from PDFs and forms."],
        ["Internal assistants", "Search company knowledge without digging through folders."],
        ["Human-in-the-loop", "Controls that prevent reckless automation."],
        ["Secure handling", "Careful data boundaries for business content."],
        ["Measurable ROI", "Projects scoped around time saved — not demos."],
      ],
      tech: ["LLM APIs", "Embeddings", "Prompt Engineering", "Node.js", "Python", "Secure Data Handling"],
      portfolioIds: ["it"],
      links: [
        { href: "software-development.html", label: "Custom Software" },
        { href: "business-automation.html", label: "Automation" },
        { href: "../pages/blog.html", label: "AI Insights" },
      ],
      faqs: [
        { q: "Is AI right for every business?", a: "Only where ROI and data readiness are clear. We recommend AI when it improves outcomes — not for trend chasing." },
        { q: "Will AI replace our staff?", a: "Our implementations assist teams. Final customer and compliance decisions stay human." },
      ],
      theme: { accent: "#06B6D4", accent2: "#67E8F9", glow: "rgba(6,182,212,0.2)", pattern: "circuit" },
    },
    {
      slug: "website-redesign",
      icon: "♻️",
      title: "Website Redesign Services Pakistan | Modernize Your Site | Onairo Solutions",
      h1: "Website Redesign That Protects Trust and Rankings",
      lead: "Refresh outdated sites with modern design, faster performance, and clearer conversion paths — without throwing away what already works.",
      meta: "Website redesign services in Pakistan. Modernize outdated business websites with better UX, speed, SEO structure, and conversion paths.",
      what: "If your site looks dated, loads slowly, or hides CTAs, a redesign can recover lost enquiries. We modernize carefully with SEO continuity in mind.",
      benefits: [
        ["Fresh visual identity", "Premium look without losing brand recognition."],
        ["Conversion upgrades", "Clearer offers, proof, and contact paths."],
        ["Performance reboot", "Faster pages and healthier Core Web Vitals."],
        ["SEO continuity", "Redirects and structure planned to protect rankings."],
        ["Mobile recovery", "Fix cramped layouts that lose phone visitors."],
        ["Content cleanup", "Rewrite confusing pages into purposeful journeys."],
      ],
      tech: ["HTML5", "CSS3", "JavaScript", "SEO Redirects", "Performance Audits"],
      portfolioIds: ["clinic", "realestate", "salon"],
      links: [
        { href: "website-development.html", label: "Website Development" },
        { href: "seo-services.html", label: "SEO Services" },
        { href: "ui-ux-design.html", label: "UI/UX Design" },
      ],
      faqs: [
        { q: "Will redesign hurt my Google rankings?", a: "Done correctly — no. We plan URL mapping, redirects, and content continuity before launch." },
        { q: "Can you keep my domain and hosting?", a: "Yes. Redesigns can deploy to your existing domain with a controlled cutover." },
      ],
      theme: { accent: "#14B8A6", accent2: "#5EEAD4", glow: "rgba(20,184,166,0.18)", pattern: "grid" },
    },
    {
      slug: "maintenance-support",
      icon: "🛠️",
      title: "Website & Software Maintenance Support | Onairo Solutions",
      h1: "Maintenance & Support That Keeps Products Healthy",
      lead: "After launch, stay protected with updates, fixes, monitoring, and continuous improvements from a team that knows your system.",
      meta: "Website and software maintenance support in Pakistan. Security updates, fixes, monitoring, and iterative improvements by Onairo Solutions.",
      what: "Software ages. Dependencies change. Content expands. Our maintenance retainers keep your website or application secure, fast, and evolving.",
      benefits: [
        ["Priority support", "Faster response when something breaks."],
        ["Security patches", "Stay current against known vulnerabilities."],
        ["Feature enhancements", "Small improvements that compound monthly."],
        ["Performance checks", "Catch regressions before customers complain."],
        ["Backup discipline", "Recovery plans for content and data."],
        ["Peace of mind", "A named partner instead of emergency freelancers."],
      ],
      tech: ["Monitoring", "Issue Tracking", "Dependency Updates", "Regression Testing", "Backups"],
      portfolioIds: ["it", "school"],
      links: [
        { href: "website-development.html", label: "Website Development" },
        { href: "software-development.html", label: "Software Development" },
        { href: "../pages/contact.html", label: "Contact Support" },
      ],
      faqs: [
        { q: "Can you maintain software you did not build?", a: "Often yes — after a discovery audit of codebase quality and risk." },
        { q: "What is included in a retainer?", a: "Response windows, update cadence, and improvement hours are scoped clearly before onboarding." },
      ],
      theme: { accent: "#64748B", accent2: "#94A3B8", glow: "rgba(100,116,139,0.2)", pattern: "bars" },
    },
    {
      slug: "seo-services",
      icon: "📈",
      title: "SEO Services Pakistan | Rank for Local & Industry Searches | Onairo Solutions",
      h1: "SEO Services Built for Service Businesses",
      lead: "Technical foundations, landing pages, and content structure that help clinics, firms, gyms, and agencies get found for the searches that matter.",
      meta: "SEO services in Pakistan for service businesses. Technical SEO, landing pages, local intent pages, and content structure by Onairo Solutions.",
      what: "We pair SEO with real website architecture: dedicated service pages, industry pages, internal links, schema, and content that matches search intent.",
      benefits: [
        ["Technical SEO", "Titles, canonicals, sitemaps, schema, and crawl hygiene."],
        ["Landing page systems", "Pages that target specific services and industries."],
        ["Local intent", "City and category pages for service businesses."],
        ["Internal linking", "Pathways that distribute authority and guide visitors."],
        ["Content clarity", "Natural keyword placement without stuffing."],
        ["Conversion alignment", "Traffic that can actually become enquiries."],
      ],
      tech: ["Schema.org", "XML Sitemaps", "Core Web Vitals", "Content Architecture", "Analytics Setup"],
      portfolioIds: ["dental", "lawfirm", "gym", "travel"],
      links: [
        { href: "website-development.html", label: "Website Development" },
        { href: "../industries/", label: "Industry Pages" },
        { href: "../pages/blog.html", label: "SEO Blog" },
      ],
      faqs: [
        { q: "How fast does SEO work?", a: "Technical fixes help quickly. Content and authority compounds over weeks and months — we set realistic expectations." },
        { q: "Do you guarantee #1 rankings?", a: "No ethical agency can. We focus on durable foundations and measurable visibility improvements." },
      ],
      theme: { accent: "#22C55E", accent2: "#86EFAC", glow: "rgba(34,197,94,0.18)", pattern: "dots" },
    },
    {
      slug: "business-automation",
      icon: "⚙️",
      title: "Business Automation Services Pakistan | Onairo Solutions",
      h1: "Business Automation That Removes Manual Busywork",
      lead: "Connect tools, automate follow-ups, and keep data consistent across your team — so people focus on work that matters.",
      meta: "Business automation services in Pakistan. Automate leads, notifications, reporting, and multi-app workflows with Onairo Solutions.",
      what: "We audit repetitive processes and automate the boring middle — lead routing, reminders, sync jobs, and status updates — with clear monitoring.",
      benefits: [
        ["Fewer manual steps", "Staff stop copying data between apps."],
        ["Faster response", "Leads and tickets move instantly."],
        ["Consistent data", "One source of truth across tools."],
        ["Audit-friendly logs", "Know what ran and when."],
        ["Scalable ops", "Handle more volume without more chaos."],
        ["Human override", "Automations assist — they don't trap you."],
      ],
      tech: ["APIs", "Webhooks", "Scheduled Jobs", "CRM Integrations", "Messaging Integrations"],
      portfolioIds: ["it", "realestate"],
      links: [
        { href: "software-development.html", label: "Custom Software" },
        { href: "ai-solutions.html", label: "AI Solutions" },
        { href: "../pages/request-quote.html", label: "Request Quote" },
      ],
      faqs: [
        { q: "What can be automated first?", a: "Lead routing, follow-up reminders, report generation, and inventory or status syncs usually deliver quick wins." },
      ],
      theme: { accent: "#F97316", accent2: "#FDBA74", glow: "rgba(249,115,22,0.18)", pattern: "hex" },
    },
  ],

  industries: [
    {
      slug: "school-website-design",
      portfolioId: "school",
      title: "School Website Design Pakistan | Academy & Education Websites | Onairo Solutions",
      h1: "School Websites That Build Parent Trust",
      lead: "Admissions, faculty, galleries, and clear contact paths — designed for schools and academies that need to look organized and approachable online.",
      meta: "School website design in Pakistan. Education websites with admissions, faculty, galleries, and WhatsApp enquiries by Onairo Solutions.",
      whyTitle: "Why Your School Needs a Modern Website",
      why: "Parents judge credibility in seconds. A clear school website answers fee and admissions questions, showcases facilities, and makes contact easy — especially on mobile.",
      whyPoints: ["Admissions clarity", "Principal message", "Faculty profiles", "Event & photo gallery", "Mobile-friendly contact", "Optional student portal links"],
      features: [
        ["Admissions section", "Steps, requirements, and enquiry CTAs."],
        ["Faculty showcase", "Teachers and leadership with trust-building bios."],
        ["Campus gallery", "Photos that sell atmosphere and facilities."],
        ["News & events", "Keep parents informed without WhatsApp spam."],
        ["Maps & contact", "Easy directions and phone/WhatsApp access."],
        ["EduTrack pathway", "Link schools toward digital office management."],
      ],
      benefits: ["More qualified admissions enquiries", "Stronger digital first impression", "Less repetitive WhatsApp answering", "Better Google visibility for school searches"],
      links: [
        { href: "../products/edutrack.html", label: "EduTrack School Software" },
        { href: "../services/software-development.html", label: "Software Development" },
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../portfolio/index.html", label: "Portfolio" },
      ],
      faqs: [
        { q: "Can parents enquire on WhatsApp?", a: "Yes. We place contextual WhatsApp CTAs for admissions and general enquiries." },
        { q: "Do you also offer school management software?", a: "Yes. EduTrack handles attendance, fees, payroll, ID cards, and more as a Windows application." },
      ],
      theme: { accent: "#0D9488", accent2: "#5EEAD4", glow: "rgba(13,148,136,0.22)", pattern: "waves", mood: "education" },
    },
    {
      slug: "law-firm-website-design",
      portfolioId: "lawfirm",
      title: "Law Firm Website Design Pakistan | Legal Website Demo | Onairo Solutions",
      h1: "Law Firm Websites That Signal Credibility",
      lead: "Practice areas, attorney profiles, and consultation booking — designed for firms that need to look established before the first call.",
      meta: "Law firm website design in Pakistan. Professional legal websites with practice areas, lawyers, and consultation booking by Onairo Solutions.",
      whyTitle: "Why Law Firms Need a Premium Website",
      why: "Clients researching counsel online look for clarity and authority. Your site should explain expertise, show people, and make booking a consultation effortless.",
      whyPoints: ["Practice area pages", "Lawyer profiles", "Case enquiry forms", "Consultation booking", "Trust & confidentiality cues", "Mobile-first contact"],
      features: [
        ["Practice areas", "Clear service pages for each legal focus."],
        ["Attorney bios", "Credentials that build confidence."],
        ["Consultation CTA", "Book calls without friction."],
        ["Case enquiry", "Capture matter details privately."],
        ["Insights section", "Thought leadership for SEO."],
        ["Confidentiality messaging", "Tone that matches legal expectations."],
      ],
      benefits: ["Higher-quality consultation requests", "Stronger professional brand", "Better local legal search presence", "Less time answering basic intake questions"],
      links: [
        { href: "../services/ui-ux-design.html", label: "UI/UX Design" },
        { href: "../services/seo-services.html", label: "SEO Services" },
        { href: "../services/website-development.html", label: "Website Development" },
      ],
      faqs: [
        { q: "Can we highlight multiple practice areas?", a: "Yes. Each practice area can have its own SEO-ready page and intake path." },
        { q: "Is the tone customizable?", a: "Absolutely — from traditional navy-gold to modern minimalist." },
      ],
      theme: { accent: "#C9A227", accent2: "#E7D39A", glow: "rgba(201,162,39,0.16)", pattern: "grid", mood: "legal" },
    },
    {
      slug: "dental-clinic-website-design",
      portfolioId: "dental",
      title: "Dental Clinic Website Design Pakistan | Patient-Focused Sites | Onairo Solutions",
      h1: "Professional Dental Clinic Websites That Build Patient Trust",
      lead: "Treatment pages, smile galleries, dentist profiles, and appointment CTAs — crafted for clinics that want more booked visits.",
      meta: "Dental clinic website design in Pakistan. Patient-friendly dental websites with treatments, smile gallery, and WhatsApp appointments.",
      whyTitle: "Why Your Clinic Needs a Website",
      why: "Patients compare clinics online before calling. A polished dental website reduces anxiety, showcases results, and makes booking appointments obvious.",
      whyPoints: ["Online appointment paths", "Google Maps directions", "Patient trust signals", "Mobile-friendly browsing", "Emergency contacts", "Treatment pages", "Smile gallery"],
      features: [
        ["Treatments", "Services explained in plain language."],
        ["Smile gallery", "Before/after proof that converts."],
        ["Dentist profiles", "Human faces build comfort."],
        ["Appointment CTAs", "WhatsApp and form booking."],
        ["Kids corner", "Family-friendly clinic storytelling."],
        ["Location & hours", "Maps and emergency info."],
      ],
      benefits: ["More appointment enquiries", "Better patient education before visits", "Stronger Google presence", "Professional clinic branding"],
      links: [
        { href: "../services/seo-services.html", label: "SEO Services" },
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../portfolio/index.html", label: "Portfolio" },
        { href: "../pages/contact.html", label: "Contact" },
      ],
      faqs: [
        { q: "Can patients book on WhatsApp?", a: "Yes. Most clinics convert best with WhatsApp appointment paths plus a clean website." },
        { q: "Do you include smile galleries?", a: "Yes — structured galleries that load fast and look premium on mobile." },
      ],
      theme: { accent: "#60A5FA", accent2: "#BFDBFE", glow: "rgba(96,165,250,0.22)", pattern: "dots", mood: "clinical" },
    },
    {
      slug: "travel-agency-website-design",
      portfolioId: "travel",
      title: "Travel Agency Website Design Pakistan | Tour & Visa Sites | Onairo Solutions",
      h1: "Travel Agency Websites That Sell Destinations",
      lead: "Packages, destination galleries, offers, and trip enquiry flows — designed for agencies that convert inspiration into bookings.",
      meta: "Travel agency website design in Pakistan. Tour websites with packages, destinations, visa services, and WhatsApp trip planning.",
      whyTitle: "Why Travel Agencies Need a Conversion Website",
      why: "Travelers browse visually. Your site should showcase destinations fast, package offers clearly, and capture trip enquiries before they bounce to competitors.",
      whyPoints: ["Tour packages", "Visa services", "Destination gallery", "Booking / enquiry form", "Offer countdowns", "WhatsApp trip planning"],
      features: [
        ["Destination stories", "Cinematic galleries that inspire."],
        ["Package cards", "Price and inclusions at a glance."],
        ["Visa services", "Support pages that reduce support load."],
        ["Enquiry forms", "Capture travel dates and party size."],
        ["Offers module", "Highlight seasonal deals."],
        ["WhatsApp CTAs", "Close trips in chat."],
      ],
      benefits: ["More package enquiries", "Better visual brand", "Faster WhatsApp conversions", "SEO pages for destinations"],
      links: [
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../services/seo-services.html", label: "SEO Services" },
        { href: "../portfolio/index.html", label: "Portfolio" },
      ],
      faqs: [
        { q: "Can we list Umrah and international packages?", a: "Yes. Packages can be categorized however your agency sells." },
      ],
      theme: { accent: "#0EA5E9", accent2: "#7DD3FC", glow: "rgba(14,165,233,0.22)", pattern: "waves", mood: "travel" },
    },
    {
      slug: "gym-website-design",
      portfolioId: "gym",
      title: "Gym Website Design Pakistan | Fitness Center Websites | Onairo Solutions",
      h1: "Gym Websites That Convert Visitors Into Members",
      lead: "Memberships, trainers, class schedules, and transformation proof — built for fitness brands that sell results.",
      meta: "Gym website design in Pakistan. Fitness websites with memberships, trainers, BMI tools, and WhatsApp join flows by Onairo Solutions.",
      whyTitle: "Why Gyms Need a High-Energy Website",
      why: "People join gyms emotionally. Your website should show energy, proof, and an easy path to membership — especially on mobile after Instagram ads.",
      whyPoints: ["Membership plans", "Trainer profiles", "BMI calculator", "Transformation gallery", "Class booking", "WhatsApp join"],
      features: [
        ["Membership pricing", "Clear plans that reduce hesitation."],
        ["Trainer roster", "Faces and specialties that build trust."],
        ["Transformations", "Before/after stories that sell."],
        ["Class schedule", "Timetable for busy members."],
        ["BMI / tools", "Interactive engagement."],
        ["Join CTA", "WhatsApp and form conversion."],
      ],
      benefits: ["More membership enquiries", "Stronger social-to-web conversion", "Professional fitness branding", "Less front-desk repetition"],
      links: [
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../services/seo-services.html", label: "SEO Services" },
        { href: "../pages/request-quote.html", label: "Get Quote" },
      ],
      faqs: [
        { q: "Can we integrate class booking later?", a: "Yes. Many gyms start with WhatsApp join flows and add booking systems next." },
      ],
      theme: { accent: "#EF4444", accent2: "#FCA5A5", glow: "rgba(239,68,68,0.2)", pattern: "bars", mood: "fitness" },
    },
    {
      slug: "restaurant-website-design",
      portfolioId: "restaurant",
      title: "Restaurant Website Design Pakistan | Menu & Reservation Sites | Onairo Solutions",
      h1: "Restaurant Websites That Make Guests Hungry to Visit",
      lead: "Menus, food photography, reservations, and location clarity — designed for restaurants that want more tables filled.",
      meta: "Restaurant website design in Pakistan. Menu showcase, reservations, food gallery, and WhatsApp ordering by Onairo Solutions.",
      whyTitle: "Why Restaurants Need More Than Social Media",
      why: "Social posts expire. A restaurant website permanently hosts your menu, gallery, hours, and reservation path — and ranks on Google Maps searches.",
      whyPoints: ["Digital menu", "Reservations", "Food gallery", "Ordering / WhatsApp", "Maps & hours", "Event catering pages"],
      features: [
        ["Menu sections", "Categories that load fast on mobile."],
        ["Food gallery", "Photography-forward layouts."],
        ["Reservation CTA", "Book tables via form or WhatsApp."],
        ["Location map", "Directions that reduce no-shows."],
        ["Offers strip", "Ramadan and weekend specials."],
        ["Brand story", "Atmosphere that matches your dining room."],
      ],
      benefits: ["More reservation enquiries", "Always-on menu access", "Better local discovery", "Stronger brand consistency"],
      links: [
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../services/seo-services.html", label: "Local SEO" },
        { href: "../portfolio/index.html", label: "Portfolio" },
      ],
      faqs: [
        { q: "Can the menu update easily?", a: "Yes. We structure menus for practical updates as dishes change." },
      ],
      theme: { accent: "#D97706", accent2: "#FBBF24", glow: "rgba(217,119,6,0.2)", pattern: "dots", mood: "hospitality" },
    },
    {
      slug: "hotel-website-design",
      portfolioId: "hotel",
      title: "Hotel Website Design Pakistan | Booking-Ready Hotel Sites | Onairo Solutions",
      h1: "Hotel Websites That Showcase Stay Experiences",
      lead: "Rooms, amenities, reviews, and booking CTAs — crafted for hotels and guest houses that sell comfort online.",
      meta: "Hotel website design in Pakistan. Rooms, amenities, reviews, and booking CTAs for hotels and guest houses by Onairo Solutions.",
      whyTitle: "Why Hotels Need a Dedicated Website",
      why: "Guests compare photos, amenities, and booking ease. A hotel site should make rooms irresistible and the next step obvious.",
      whyPoints: ["Room galleries", "Booking CTA", "Amenities list", "Guest reviews", "Location maps", "WhatsApp reservations"],
      features: [
        ["Room types", "Photo-led room pages."],
        ["Amenities", "Pool, parking, breakfast, Wi-Fi clarity."],
        ["Booking path", "Form or partner booking links."],
        ["Reviews module", "Social proof near CTAs."],
        ["Location story", "Neighborhood and map."],
        ["Offers", "Seasonal stay packages."],
      ],
      benefits: ["Direct booking enquiries", "Stronger brand vs OTAs", "Better photo storytelling", "Mobile-ready guest journeys"],
      links: [
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../services/ui-ux-design.html", label: "UI/UX Design" },
        { href: "../pages/request-quote.html", label: "Request Quote" },
      ],
      faqs: [
        { q: "Is a hotel demo available?", a: "A Harborview Hotel demo is in the portfolio roadmap — we can still build a custom hotel site now." },
      ],
      theme: { accent: "#1D4ED8", accent2: "#93C5FD", glow: "rgba(29,78,216,0.2)", pattern: "waves", mood: "hotel" },
    },
    {
      slug: "construction-company-website",
      portfolioId: "building",
      title: "Construction Company Website Design | Project Showcase Sites | Onairo Solutions",
      h1: "Construction Websites That Prove Capability",
      lead: "Projects, timelines, safety messaging, and enquiry paths — built for developers and contractors who sell trust.",
      meta: "Construction company website design. Project showcases, progress timelines, amenities, and lead capture for builders by Onairo Solutions.",
      whyTitle: "Why Construction Brands Need a Project Website",
      why: "Buyers want proof of delivery. A construction site should showcase projects, progress, and professionalism before a site visit.",
      whyPoints: ["Project portfolio", "Safety messaging", "Services list", "Equipment / capability", "Progress timelines", "Lead forms"],
      features: [
        ["Project gallery", "Completed and ongoing works."],
        ["Progress tracker", "Visual timelines for under-construction projects."],
        ["Unit availability", "For residential launches."],
        ["Amenities", "Lifestyle selling points."],
        ["Developer story", "Credibility and track record."],
        ["Enquiry CTA", "WhatsApp and form capture."],
      ],
      benefits: ["Higher-quality project enquiries", "Clearer brand authority", "Better investor and buyer confidence", "SEO for project names"],
      links: [
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../industries/real-estate-website.html", label: "Real Estate Websites" },
        { href: "../portfolio/index.html", label: "Portfolio" },
      ],
      faqs: [
        { q: "Can we show live construction progress?", a: "Yes. Progress bars and timeline sections are a highlight of our construction demos." },
      ],
      theme: { accent: "#78716C", accent2: "#D6D3D1", glow: "rgba(120,113,108,0.2)", pattern: "bars", mood: "construction" },
    },
    {
      slug: "real-estate-website",
      portfolioId: "realestate",
      title: "Real Estate Website Design Pakistan | Property Listing Sites | Onairo Solutions",
      h1: "Real Estate Websites Built for Property Enquiries",
      lead: "Listings, search, agents, and maps — designed for agencies that need faster WhatsApp and call responses.",
      meta: "Real estate website design in Pakistan. Property listing websites with search, agents, maps, and WhatsApp enquiries.",
      whyTitle: "Why Agencies Need a Listing Website",
      why: "Buyers filter properties online. Your website should help them search, shortlist, and enquire without friction.",
      whyPoints: ["Property listings", "Property search", "Agent profiles", "Maps", "Verified badges", "WhatsApp enquiry"],
      features: [
        ["Listing cards", "Photos, price, and key specs."],
        ["Search & filters", "City, type, budget."],
        ["Agent pages", "Human trust for big purchases."],
        ["Map views", "Location context."],
        ["Enquiry CTAs", "WhatsApp and forms on every listing."],
        ["Featured inventory", "Highlight premium properties."],
      ],
      benefits: ["More property enquiries", "Organized inventory presentation", "Stronger agency brand", "Faster response workflows"],
      links: [
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../services/software-development.html", label: "Custom CRM Options" },
        { href: "../industries/construction-company-website.html", label: "Construction Sites" },
      ],
      faqs: [
        { q: "Can listings sync from a spreadsheet later?", a: "Yes. Many agencies start manual and automate inventory updates as they grow." },
      ],
      theme: { accent: "#1E3A8A", accent2: "#93C5FD", glow: "rgba(30,58,138,0.22)", pattern: "grid", mood: "realestate" },
    },
    {
      slug: "rent-a-car-website",
      portfolioId: "carrental",
      title: "Rent A Car Website Design Pakistan | Fleet & Booking Sites | Onairo Solutions",
      h1: "Rent-a-Car Websites That Showcase Your Fleet",
      lead: "Vehicle catalogues, booking widgets, pricing, and chauffeur options — designed for rental businesses that sell availability fast.",
      meta: "Rent a car website design in Pakistan. Fleet catalogues, booking forms, pricing, and WhatsApp reservations by Onairo Solutions.",
      whyTitle: "Why Car Rental Businesses Need a Fleet Website",
      why: "Customers compare cars and prices quickly. A rental site should filter the fleet, show photos, and capture bookings before they call a competitor.",
      whyPoints: ["Vehicle catalogue", "360° / gallery views", "Booking form", "Fleet filters", "Pricing clarity", "Insurance information"],
      features: [
        ["Fleet grid", "Filter by type and budget."],
        ["Vehicle detail pages", "Specs and photo galleries."],
        ["Booking widget", "Dates and pickup details."],
        ["Chauffeur options", "Upsell premium services."],
        ["Pricing tables", "Transparent rental rates."],
        ["WhatsApp reserve", "Close deals in chat."],
      ],
      benefits: ["More reservation enquiries", "Clearer fleet presentation", "Less phone tag", "Professional rental brand"],
      links: [
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../services/ecommerce-development.html", label: "Catalogue Experiences" },
        { href: "../portfolio/index.html", label: "Portfolio" },
      ],
      faqs: [
        { q: "Can we show airport pickup options?", a: "Yes. Booking forms and service pages can include airport and chauffeur packages." },
      ],
      theme: { accent: "#DC2626", accent2: "#FCA5A5", glow: "rgba(220,38,38,0.2)", pattern: "hex", mood: "automotive" },
    },
    {
      slug: "it-company-website",
      portfolioId: "it",
      title: "IT Company Website Design Pakistan | Software Firm Sites | Onairo Solutions",
      h1: "IT Company Websites That Look Enterprise-Ready",
      lead: "Services, case studies, tech stacks, and consultation forms — designed for software and technology brands.",
      meta: "IT company website design in Pakistan. SaaS-style tech websites with services, projects, case studies, and consultation CTAs.",
      whyTitle: "Why Tech Companies Need a Credible Website",
      why: "B2B buyers evaluate seriousness online. Your site should communicate capability, process, and outcomes — not just buzzwords.",
      whyPoints: ["Services", "Projects / case studies", "Technology stack", "Team", "Careers", "Consultation enquiry"],
      features: [
        ["Services architecture", "Clear offers for each capability."],
        ["Case studies", "Proof over promises."],
        ["Tech stack", "Credibility for technical buyers."],
        ["Solutions pages", "Industry or product angles."],
        ["Careers module", "Hiring presence."],
        ["Consultation CTA", "Enterprise enquiry path."],
      ],
      benefits: ["Higher-quality leads", "Stronger brand authority", "Better recruiting presence", "SEO for service keywords"],
      links: [
        { href: "../services/software-development.html", label: "Software Development" },
        { href: "../services/ai-solutions.html", label: "AI Solutions" },
        { href: "../services/website-development.html", label: "Website Development" },
      ],
      faqs: [
        { q: "Can this match a dark SaaS aesthetic?", a: "Yes. Our NEXORA-style demo is built for modern tech brands." },
      ],
      theme: { accent: "#3B82F6", accent2: "#818CF8", glow: "rgba(59,130,246,0.22)", pattern: "circuit", mood: "tech" },
    },
    {
      slug: "medical-clinic-website",
      portfolioId: "clinic",
      title: "Medical Clinic Website Design Pakistan | Doctor & Appointment Sites | Onairo Solutions",
      h1: "Medical Clinic Websites Patients Trust",
      lead: "Doctors, departments, appointments, and emergency contacts — designed for clinics that need calm, clear digital presence.",
      meta: "Medical clinic website design in Pakistan. Doctor profiles, departments, appointments, and emergency contacts by Onairo Solutions.",
      whyTitle: "Why Clinics Need a Patient-First Website",
      why: "Patients search symptoms, specialties, and doctors. A clinic website should reduce confusion and make booking the obvious next step.",
      whyPoints: ["Doctor profiles", "Appointments", "Departments", "Emergency contacts", "Services list", "Mobile access"],
      features: [
        ["Doctor directory", "Specialties and timings."],
        ["Departments", "Clear navigation for care types."],
        ["Appointment CTA", "WhatsApp and forms."],
        ["Emergency info", "Visible when urgent."],
        ["Patient education", "Services explained simply."],
        ["Location & parking", "Practical visit details."],
      ],
      benefits: ["More appointment bookings", "Reduced front-desk load", "Professional healthcare brand", "Better mobile patient journeys"],
      links: [
        { href: "../industries/dental-clinic-website-design.html", label: "Dental Clinic Sites" },
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../services/seo-services.html", label: "SEO Services" },
      ],
      faqs: [
        { q: "Can we list multiple doctors and timings?", a: "Yes. Doctor directories scale with your roster." },
      ],
      theme: { accent: "#0891B2", accent2: "#67E8F9", glow: "rgba(8,145,178,0.2)", pattern: "waves", mood: "medical" },
    },
    {
      slug: "salon-website",
      portfolioId: "salon",
      title: "Salon Website Design Pakistan | Beauty Salon Booking Sites | Onairo Solutions",
      h1: "Salon Websites That Book Appointments",
      lead: "Services, pricing, before/after galleries, and WhatsApp booking — designed for beauty brands that sell transformation.",
      meta: "Salon website design in Pakistan. Beauty salon sites with services, pricing, galleries, and WhatsApp appointment booking.",
      whyTitle: "Why Salons Need a Booking Website",
      why: "Clients want prices, results, and availability. A salon website answers those questions and converts Instagram traffic into appointments.",
      whyPoints: ["Services & pricing", "Before/after gallery", "Team profiles", "WhatsApp booking", "Offers", "Mobile-first look"],
      features: [
        ["Service menu", "Clear pricing tables."],
        ["Gallery", "Results-focused photography."],
        ["Stylist profiles", "Personal brand for each artist."],
        ["Booking CTA", "WhatsApp appointment steps."],
        ["Offers banner", "Seasonal packages."],
        ["Brand mood", "Soft premium aesthetics."],
      ],
      benefits: ["More booked appointments", "Less price negotiation chat", "Stronger Instagram-to-web funnel", "Professional beauty branding"],
      links: [
        { href: "../industries/barber-shop-website.html", label: "Barber Shop Sites" },
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../services/ui-ux-design.html", label: "UI/UX Design" },
      ],
      faqs: [
        { q: "Can pricing differ by stylist?", a: "Yes. Menus can be structured however you sell services." },
      ],
      theme: { accent: "#DB2777", accent2: "#F9A8D4", glow: "rgba(219,39,119,0.18)", pattern: "dots", mood: "beauty" },
    },
    {
      slug: "barber-shop-website",
      portfolioId: "menssalon",
      title: "Barber Shop Website Design | Mens Salon Booking Sites | Onairo Solutions",
      h1: "Barber Shop Websites With Modern Style",
      lead: "Pricing tables, masonry galleries, barber profiles, and WhatsApp booking — built for shops that sell craft and consistency.",
      meta: "Barber shop website design. Mens salon websites with pricing, galleries, barber profiles, and WhatsApp booking by Onairo Solutions.",
      whyTitle: "Why Barber Shops Need a Sharp Website",
      why: "Style-conscious clients check vibes online. Your site should show cuts, prices, and an easy booking path.",
      whyPoints: ["Pricing table", "Gallery", "Barber profiles", "WhatsApp booking", "Location", "Brand storytelling"],
      features: [
        ["Service pricing", "Transparent cut and package rates."],
        ["Masonry gallery", "Cuts that sell the craft."],
        ["Barber bios", "Personal trust."],
        ["Booking steps", "WhatsApp flow that feels premium."],
        ["Hours & map", "Visit logistics."],
        ["Dark aesthetic", "Modern barbershop mood."],
      ],
      benefits: ["More appointments", "Clearer pricing communication", "Stronger local brand", "Better social conversion"],
      links: [
        { href: "../industries/salon-website.html", label: "Salon Websites" },
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../pages/request-quote.html", label: "Get This Website" },
      ],
      faqs: [
        { q: "Can we match a dark premium look?", a: "Yes. Our Gentlemen's Cut demo is built for modern barbershop aesthetics." },
      ],
      theme: { accent: "#A16207", accent2: "#FDE68A", glow: "rgba(161,98,7,0.18)", pattern: "bars", mood: "barber" },
    },
    {
      slug: "accounting-firm-website",
      portfolioId: "lawfirm",
      title: "Accounting Firm Website Design Pakistan | CA & Finance Sites | Onairo Solutions",
      h1: "Accounting Firm Websites That Feel Precise and Trustworthy",
      lead: "Services, team credibility, and consultation CTAs — designed for CA firms and finance advisors who sell expertise.",
      meta: "Accounting firm website design in Pakistan. Professional finance and CA websites with services, team profiles, and consultation booking.",
      whyTitle: "Why Accounting Firms Need a Professional Website",
      why: "Finance clients look for clarity and competence. Your website should explain services, show credentials, and make consultation requests simple.",
      whyPoints: ["Service pages", "Team credentials", "Consultation booking", "Compliance tone", "Resource articles", "Secure contact"],
      features: [
        ["Service catalogue", "Audit, tax, advisory clarity."],
        ["Team profiles", "Credentials that reassure."],
        ["Consultation CTA", "Book discovery calls."],
        ["Insights blog", "SEO for finance topics."],
        ["Client process", "How engagement works."],
        ["Confidential contact", "Professional enquiry forms."],
      ],
      benefits: ["More consultation requests", "Stronger professional brand", "Better service SEO", "Clearer client onboarding"],
      links: [
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../services/seo-services.html", label: "SEO Services" },
        { href: "../services/ui-ux-design.html", label: "UI/UX Design" },
      ],
      faqs: [
        { q: "Do you have an accounting-specific demo?", a: "We adapt our professional services layouts for CA and finance firms with industry-specific content and tone." },
      ],
      theme: { accent: "#0F766E", accent2: "#5EEAD4", glow: "rgba(15,118,110,0.2)", pattern: "grid", mood: "finance" },
    },
    {
      slug: "clothing-store-website",
      portfolioId: "boutique",
      title: "Clothing Store Website Design | Boutique Ecommerce Sites | Onairo Solutions",
      h1: "Clothing Store Websites That Showcase Collections",
      lead: "Product galleries, collection stories, and WhatsApp ordering — designed for boutiques that sell style online.",
      meta: "Clothing store website design. Boutique websites with collections, product galleries, and WhatsApp ordering by Onairo Solutions.",
      whyTitle: "Why Boutiques Need a Collection Website",
      why: "Fashion sells visually. A boutique site should present collections beautifully and move shoppers into WhatsApp or checkout quickly.",
      whyPoints: ["Product gallery", "Collections", "WhatsApp order", "Lookbook", "Mobile shopping", "Brand story"],
      features: [
        ["Collection pages", "Seasonal storytelling."],
        ["Product grid", "Fast visual browsing."],
        ["WhatsApp order", "Assisted commerce for Pakistan."],
        ["Instagram bridge", "Social-to-site continuity."],
        ["Size / info blocks", "Reduce order confusion."],
        ["Brand mood", "Fashion-forward aesthetics."],
      ],
      benefits: ["More product enquiries", "Stronger brand presence", "Better Instagram conversion", "Organised catalogue"],
      links: [
        { href: "../services/ecommerce-development.html", label: "Ecommerce Development" },
        { href: "../services/website-development.html", label: "Website Development" },
        { href: "../portfolio/index.html", label: "Portfolio" },
      ],
      faqs: [
        { q: "Do we need full ecommerce checkout?", a: "Not always. Many boutiques convert best with WhatsApp ordering plus a polished catalogue." },
      ],
      theme: { accent: "#7C3AED", accent2: "#C4B5FD", glow: "rgba(124,58,237,0.2)", pattern: "dots", mood: "fashion" },
    },
  ],
};
